---

# All tasks about uwsgi configuration

- name: 'CONFIG | Ensure uwsgi group exists'
  group:
    name: "{{ uwsgi_group }}"
    state: present
  when: uwsgi_ensure_user_group_exists

- name: 'CONFIG | Ensure uwsgi user exists'
  user:
    name: "{{ uwsgi_user }}"
    group: "{{ uwsgi_group }}"
    shell: /bin/false
    state: present
  when: uwsgi_ensure_user_group_exists

- name: 'CONFIG | Ensure log directories exist 4 uswgi'
  file:
    path: "{{ uwsgi_config_log_path }}"
    state: 'directory'
    owner: "{{ uwsgi_user }}"
    group: "{{ uwsgi_group }}"
    mode: '0775'
  when: 'not uwsgi_install_emperor'

- name: 'CONFIG | Ensure log directories exist 4 uwsgi-emperor'
  file:
    path: "{{ uwsgi_config_log_path }}"
    state: 'directory'
    owner: "{{ uwsgi_emperor_user }}"
    group: "{{ uwsgi_emperor_group }}"
    mode: '0775'
  when: 'uwsgi_install_emperor'

- name: 'CONFIG | Create app configuration files'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest_available }}/{{ item.name }}.yml"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: 'HANDLER | Restart uwsgi'
  with_items: "{{ uwsgi_apps_defaults }}"
  when: 'not uwsgi_install_emperor'

- name: 'CONFIG | create systemd uwsgi-emperor'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ uwsgi_systemd }}"
  register: 'uwsgi_systemd_config_updated'
  when:
    - 'uwsgi_install_emperor'
    - 'uwsgi_systemd'

- name: 'CONFIG | delete init.d uwsgi-emperor file'
  file:
    path: '/etc/init.d/uwsgi-emperor'
    state: 'absent'
  register: 'delete_initd_uwsgi_emperor_file'
  when:
    - 'uwsgi_install_emperor'
    - 'uwsgi_is_systemd_managed'


- name: 'CONFIG | disable init.d uwsgi-emperor'
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ init_d_disable }}"
  when:
    - 'uwsgi_install_emperor'
    - 'uwsgi_is_systemd_managed'
    - 'delete_initd_uwsgi_emperor_file.changed'

- name: 'HANDLER | force systemd to reread configs'
  systemd:
    daemon_reload: True
  when:
    - 'uwsgi_is_systemd_managed'
    - 'uwsgi_systemd_config_updated.changed'

- name: 'CONFIG | Create emperor configuration files'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: 'HANDLER | Start uwsgi emperor'
  with_items: "{{ uwsgi_emperor }}"
  when: 'uwsgi_install_emperor'

- name: 'CONFIG | Create app configuration files 4 emperor'
  template:
    src: "{{ item.src }}"
    dest: "{{ uwsgi_emperor_vassals_config_path }}/{{ item.name }}.yml"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ uwsgi_apps_defaults }}"
  when: 'uwsgi_install_emperor'

- name: 'CONFIG | Activate needed applications'
  file:
    src: "{{ item.dest_available }}/{{ item.name }}.yml"
    dest: "{{ item.dest_enabled }}/{{ item.name }}.yml"
    state: 'link'
  notify: 'HANDLER | Restart uwsgi'
  with_items: "{{ uwsgi_apps_defaults }}"
  when: 'not uwsgi_install_emperor'
